server:
  port: 8089
spring:
  application:
    name: JobSearch
  mvc:
    static-path-pattern: /static/**
  freemarker:
    expose-session-attributes: true

  # ------------- DataBases
  datasource:
    url: jdbc:h2:./db/JobSearch;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

  # ------------- JPA Settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  # ------------- Cache Settings
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s

logging:
  level:
    root: info
    org:
      springframework:
        security: debug
    com:
      example:
        JobSearch: debug

app:
  avatar_dir: avatars