server:
  port: 8089
spring:
  application:
    name: JobSearch

  # ------------- DataBases
  datasource:
    url: jdbc:h2:./db/JobSearch;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql