INSERT INTO resumes (applicant_id, name, category_id, salary, is_active, created_date, update_time)
VALUES
    (1, 'Software Engineer', 2, 60000, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (1, 'Data Scientist', 2, 70000, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (5, 'Project Manager', 1, 75000, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (5, 'QA Engineer', 2, 55000, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (8, 'DevOps Engineer', 1, 65000, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (8, 'UI/UX Designer', 2, 60000, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (9, 'Backend Developer', 1, 80000, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (9, 'Frontend Developer', 2, 75000, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (10, 'System Administrator', 1, 70000, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (10, 'Product Manager', 2, 90000, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (13, 'Marketing Specialist', 1, 60000, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (13, 'HR Manager', 2, 65000, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (1, 'Business Analyst', 1, 70000, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (5, 'Network Engineer', 1, 75000, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (8, 'Security Specialist', 2, 80000, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);